services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .data:/var/www/html/PhpGedView/data  # Persistent storage for SQLite database