services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - phpgedview-data:/var/www/html/data  # Persists the SQLite database and data directory
volumes:
  phpgedview-data:
    driver: local